spring:
  application:
    name: mtgmarket
  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:postgresql://localhost:5432/mtgmarket
    username: apiuser
    password: apipass
    hikari:
      max-lifetime: 600000
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console.enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format-sql: true
#    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      schema-locations: classpath:migrations/create_card_table.sql, classpath:migrations/create_listing_table.sql

external:
  serra: https://cardshop-serra.com
  hareruya: https://www.hareruyamtg.com
  scryfall: https://api.scryfall.com
